-- Inserção de clínicas veterinárias
INSERT INTO dbapa.empresas (cd_empresa, nm_empresa, cnpj, sn_ativo, endereco, telefone, email)
VALUES (101, 'Clínica Veterinária PetCare', '12.345.678/0001-90', 'S', 'Rua das Flores, 123, São Paulo, SP', '(11) 1234-5678', 'contato@petcare.com.br');

INSERT INTO dbapa.empresas (cd_empresa, nm_empresa, cnpj, sn_ativo, endereco, telefone, email)
VALUES (102, 'Hospital Veterinário Animalis', '98.765.432/0001-01', 'S', 'Avenida Paulista, 456, São Paulo, SP', '(11) 9876-5432', 'contato@animalis.com.br');


--Funcionarios
INSERT INTO dbapa.funcionarios (cd_func, cd_empresa, nm_func, data_nascim_func, sexo_func, estado_civil, nacionalidade, cpf, rg, titulo_eleitor, endereco_func, telefone_func, email_func, sn_ativo_func, nome_contato_emergencia, parentesco_emergencia, telefone_emergencia, banco, agencia, conta_corrente, cargo, departamento, data_admissao, jornada_trabalho, tipo_contrato, salario, beneficios, local_trabalho, regime_trabalho, data_assinatura_contrato, exame_admissional, comprovante_endereco, foto_func, dependentes, observacoes)
VALUES (1, 101, 'Dr. João Silva', TO_DATE('1985-05-15', 'YYYY-MM-DD'), 'M', 'Solteiro', 'Brasileiro', '12345678901', 'MG1234567', '123456789012', 'Rua A, 123 - Centro, São Paulo, SP', '(11) 98765-4321', 'joao.silva@petcare.com.br', 'S', 'Maria Silva', 'Mãe', '(11) 98765-4322', 'Banco do Brasil', '1234', '1234567890', 'Veterinário', 'Veterinária', TO_DATE('2020-01-10', 'YYYY-MM-DD'), '8 horas', 'CLT', 5000.00, 'Vale alimentação, plano de saúde', 'Rua B, 456, Clínica PetCare', 'Presencial', TO_DATE('2020-01-05', 'YYYY-MM-DD'), 'S', 'S', 'S', 'N', 'Especialista em cirurgias veterinárias e atendimento de emergência.');

INSERT INTO dbapa.funcionarios (cd_func, cd_empresa, nm_func, data_nascim_func, sexo_func, estado_civil, nacionalidade, cpf, rg, titulo_eleitor, endereco_func, telefone_func, email_func, sn_ativo_func, nome_contato_emergencia, parentesco_emergencia, telefone_emergencia, banco, agencia, conta_corrente, cargo, departamento, data_admissao, jornada_trabalho, tipo_contrato, salario, beneficios, local_trabalho, regime_trabalho, data_assinatura_contrato, exame_admissional, comprovante_endereco, foto_func, dependentes, observacoes)
VALUES (2, 101, 'Ana Oliveira', TO_DATE('1990-07-20', 'YYYY-MM-DD'), 'F', 'Casada', 'Brasileira', '23456789012', 'SP2345678', '234567890123', 'Rua C, 789 - Bairro Y, São Paulo, SP', '(11) 93456-7890', 'ana.oliveira@petcare.com.br', 'S', 'Carlos Oliveira', 'Marido', '(11) 93456-7891', 'Caixa Econômica Federal', '5678', '9876543210', 'Recepcionista', 'Atendimento', TO_DATE('2021-06-15', 'YYYY-MM-DD'), '6 horas', 'PJ', 2800.00, 'Vale transporte, plano odontológico', 'Rua D, 123, Clínica PetCare', 'Home office', TO_DATE('2021-06-10', 'YYYY-MM-DD'), 'S', 'S', 'S', 'S', 'Excelente comunicação e bom atendimento ao público.');

INSERT INTO dbapa.funcionarios (cd_func, cd_empresa, nm_func, data_nascim_func, sexo_func, estado_civil, nacionalidade, cpf, rg, titulo_eleitor, endereco_func, telefone_func, email_func, sn_ativo_func, nome_contato_emergencia, parentesco_emergencia, telefone_emergencia, banco, agencia, conta_corrente, cargo, departamento, data_admissao, jornada_trabalho, tipo_contrato, salario, beneficios, local_trabalho, regime_trabalho, data_assinatura_contrato, exame_admissional, comprovante_endereco, foto_func, dependentes, observacoes)
VALUES (3, 101, 'Beatriz Lima', TO_DATE('1995-04-20', 'YYYY-MM-DD'), 'F', 'Solteira', 'Brasileira', '56789012345', 'SP5678901', '567890123456', 'Rua F, 101 - Bairro Central, São Paulo, SP', '(11) 91234-5678', 'beatriz.lima@petcare.com.br', 'S', 'Renato Lima', 'Pai', '(11) 91234-5679', 'Bradesco', '1234', '5678901234', 'Assistente de Veterinária', 'Veterinária', TO_DATE('2021-03-10', 'YYYY-MM-DD'), '8 horas', 'CLT', 3200.00, 'Vale alimentação, plano de saúde', 'Rua A, 456, Clínica PetCare', 'Presencial', TO_DATE('2021-03-08', 'YYYY-MM-DD'), 'S', 'S', 'S', 'N', 'Muito cuidadosa com os animais, ajuda com a administração de medicamentos.');

INSERT INTO dbapa.funcionarios (cd_func, cd_empresa, nm_func, data_nascim_func, sexo_func, estado_civil, nacionalidade, cpf, rg, titulo_eleitor, endereco_func, telefone_func, email_func, sn_ativo_func, nome_contato_emergencia, parentesco_emergencia, telefone_emergencia, banco, agencia, conta_corrente, cargo, departamento, data_admissao, jornada_trabalho, tipo_contrato, salario, beneficios, local_trabalho, regime_trabalho, data_assinatura_contrato, exame_admissional, comprovante_endereco, foto_func, dependentes, observacoes)
VALUES (4, 101, 'Juliana Costa', TO_DATE('1992-02-11', 'YYYY-MM-DD'), 'F', 'Casada', 'Brasileira', '67890123456', 'SP6789012', '678901234567', 'Rua G, 202 - Bairro Alto, São Paulo, SP', '(11) 92345-6789', 'juliana.costa@petcare.com.br', 'S', 'Eduardo Costa', 'Marido', '(11) 92345-6790', 'Itaú', '4321', '6789012345', 'Enfermeira Veterinária', 'Atendimento', TO_DATE('2020-12-01', 'YYYY-MM-DD'), '8 horas', 'CLT', 4000.00, 'Vale transporte, plano odontológico', 'Rua F, 300, Clínica PetCare', 'Presencial', TO_DATE('2020-11-28', 'YYYY-MM-DD'), 'S', 'S', 'S', 'S', 'Profissional com vasta experiência em procedimentos de enfermagem veterinária.');

INSERT INTO dbapa.funcionarios (cd_func, cd_empresa, nm_func, data_nascim_func, sexo_func, estado_civil, nacionalidade, cpf, rg, titulo_eleitor, endereco_func, telefone_func, email_func, sn_ativo_func, nome_contato_emergencia, parentesco_emergencia, telefone_emergencia, banco, agencia, conta_corrente, cargo, departamento, data_admissao, jornada_trabalho, tipo_contrato, salario, beneficios, local_trabalho, regime_trabalho, data_assinatura_contrato, exame_admissional, comprovante_endereco, foto_func, dependentes, observacoes)
VALUES (5, 101, 'Roberta Almeida', TO_DATE('1988-11-05', 'YYYY-MM-DD'), 'F', 'Divorciada', 'Brasileira', '78901234567', 'SP7890123', '789012345678', 'Rua H, 305 - Vila Nova, São Paulo, SP', '(11) 93456-7890', 'roberta.almeida@petcare.com.br', 'S', 'Carlos Almeida', 'Ex-marido', '(11) 93456-7891', 'Santander', '9876', '7890123456', 'Coordenadora de Atendimento', 'Administração', TO_DATE('2019-07-10', 'YYYY-MM-DD'), '8 horas', 'CLT', 4500.00, 'Vale refeição, plano de saúde', 'Rua I, 102, Clínica PetCare', 'Presencial', TO_DATE('2019-07-05', 'YYYY-MM-DD'), 'S', 'S', 'S', 'N', 'Líder de equipe de atendimento, otimização de processos no agendamento de consultas.');

INSERT INTO dbapa.funcionarios (cd_func, cd_empresa, nm_func, data_nascim_func, sexo_func, estado_civil, nacionalidade, cpf, rg, titulo_eleitor, endereco_func, telefone_func, email_func, sn_ativo_func, nome_contato_emergencia, parentesco_emergencia, telefone_emergencia, banco, agencia, conta_corrente, cargo, departamento, data_admissao, jornada_trabalho, tipo_contrato, salario, beneficios, local_trabalho, regime_trabalho, data_assinatura_contrato, exame_admissional, comprovante_endereco, foto_func, dependentes, observacoes)
VALUES (6, 102, 'Dr. Felipe Martins', TO_DATE('1980-08-10', 'YYYY-MM-DD'), 'M', 'Casado', 'Brasileiro', '89012345678', 'SP8901234', '890123456789', 'Rua I, 123 - Bairro Jardim, São Paulo, SP', '(11) 95678-9876', 'felipe.martins@animalis.com.br', 'S', 'Tatiane Martins', 'Esposa', '(11) 95678-9877', 'Bradesco', '3210', '8901234567', 'Veterinário', 'Veterinária', TO_DATE('2018-02-15', 'YYYY-MM-DD'), '8 horas', 'CLT', 5500.00, 'Vale alimentação, plano de saúde', 'Av. Paulista, 456, Hospital Animalis', 'Presencial', TO_DATE('2018-02-10', 'YYYY-MM-DD'), 'S', 'S', 'S', 'N', 'Veterinário especializado em cardiologia veterinária.');

INSERT INTO dbapa.funcionarios (cd_func, cd_empresa, nm_func, data_nascim_func, sexo_func, estado_civil, nacionalidade, cpf, rg, titulo_eleitor, endereco_func, telefone_func, email_func, sn_ativo_func, nome_contato_emergencia, parentesco_emergencia, telefone_emergencia, banco, agencia, conta_corrente, cargo, departamento, data_admissao, jornada_trabalho, tipo_contrato, salario, beneficios, local_trabalho, regime_trabalho, data_assinatura_contrato, exame_admissional, comprovante_endereco, foto_func, dependentes, observacoes)
VALUES (7, 102, 'Tatiane Souza', TO_DATE('1993-01-25', 'YYYY-MM-DD'), 'F', 'Solteira', 'Brasileira', '90123456789', 'SP9012345', '901234567890', 'Rua J, 100 - Vila Santa, São Paulo, SP', '(11) 98765-4321', 'tatiane.souza@animalis.com.br', 'S', 'Carlos Souza', 'Pai', '(11) 98765-4322', 'Itaú', '5678', '9012345678', 'Auxiliar de Atendimento Veterinário', 'Atendimento', TO_DATE('2022-01-10', 'YYYY-MM-DD'), '8 horas', 'CLT', 2800.00, 'Vale refeição, plano odontológico', 'Av. Paulista, 456, Hospital Animalis', 'Presencial', TO_DATE('2022-01-05', 'YYYY-MM-DD'), 'S', 'S', 'S', 'S', 'Excelente relacionamento com os donos de animais e cuidados com os pacientes.');

INSERT INTO dbapa.funcionarios (cd_func, cd_empresa, nm_func, data_nascim_func, sexo_func, estado_civil, nacionalidade, cpf, rg, titulo_eleitor, endereco_func, telefone_func, email_func, sn_ativo_func, nome_contato_emergencia, parentesco_emergencia, telefone_emergencia, banco, agencia, conta_corrente, cargo, departamento, data_admissao, jornada_trabalho, tipo_contrato, salario, beneficios, local_trabalho, regime_trabalho, data_assinatura_contrato, exame_admissional, comprovante_endereco, foto_func, dependentes, observacoes)
VALUES (8, 102, 'Júlia Oliveira', TO_DATE('1998-05-05', 'YYYY-MM-DD'), 'F', 'Solteira', 'Brasileira', '23456789012', 'SP2345678', '234567890123', 'Rua K, 150 - Vila S, São Paulo, SP', '(11) 92222-3344', 'julia.oliveira@animalis.com.br', 'S', 'Paula Oliveira', 'Mãe', '(11) 92222-3345', 'Bradesco', '4321', '2345678901', 'Recepcionista', 'Atendimento', TO_DATE('2022-02-01', 'YYYY-MM-DD'), '6 horas', 'PJ', 2500.00, 'Vale transporte, plano odontológico', 'Av. Paulista, 456, Hospital Animalis', 'Home office', TO_DATE('2022-01-30', 'YYYY-MM-DD'), 'S', 'S', 'S', 'N', 'Habilidade em lidar com agendamento e atendimento ao cliente.');

INSERT INTO dbapa.funcionarios (cd_func, cd_empresa, nm_func, data_nascim_func, sexo_func, estado_civil, nacionalidade, cpf, rg, titulo_eleitor, endereco_func, telefone_func, email_func, sn_ativo_func, nome_contato_emergencia, parentesco_emergencia, telefone_emergencia, banco, agencia, conta_corrente, cargo, departamento, data_admissao, jornada_trabalho, tipo_contrato, salario, beneficios, local_trabalho, regime_trabalho, data_assinatura_contrato, exame_admissional, comprovante_endereco, foto_func, dependentes, observacoes)
VALUES (9, 102, 'Dr. Carlos Pereira', TO_DATE('1982-03-30', 'YYYY-MM-DD'), 'M', 'Divorciado', 'Brasileiro', '34567890123', 'RJ3456789', '345678901234', 'Rua E, 101 - Zona Leste, São Paulo, SP', '(21) 95678-1234', 'carlos.pereira@animalis.com.br', 'S', 'Luiza Pereira', 'Filha', '(21) 95678-1235', 'Santander', '4321', '1230987654', 'Veterinário', 'Atendimento', TO_DATE('2019-08-01', 'YYYY-MM-DD'), '8 horas', 'CLT', 6000.00, 'Vale alimentação, plano de saúde', 'Av. F, 789, Hospital Animalis', 'Híbrido', TO_DATE('2019-07-28', 'YYYY-MM-DD'), 'S', 'S', 'S', 'N', 'Experiência em emergências e cirurgias de médio e grande porte.');

INSERT INTO dbapa.funcionarios (cd_func, cd_empresa, nm_func, data_nascim_func, sexo_func, estado_civil, nacionalidade, cpf, rg, titulo_eleitor, endereco_func, telefone_func, email_func, sn_ativo_func, nome_contato_emergencia, parentesco_emergencia, telefone_emergencia, banco, agencia, conta_corrente, cargo, departamento, data_admissao, jornada_trabalho, tipo_contrato, salario, beneficios, local_trabalho, regime_trabalho, data_assinatura_contrato, exame_admissional, comprovante_endereco, foto_func, dependentes, observacoes)
VALUES (10, 102, 'Mariana Souza', TO_DATE('1994-08-15', 'YYYY-MM-DD'), 'F', 'Solteira', 'Brasileira', '45678901234', 'SP4567890', '456789012345', 'Rua G, 200 - Vila Nova, São Paulo, SP', '(31) 93456-1234', 'mariana.souza@animalis.com.br', 'S', 'Fernanda Souza', 'Mãe', '(31) 93456-1235', 'Bradesco', '6789', '4567890123', 'Assistente de Veterinária', 'Atendimento', TO_DATE('2022-02-12', 'YYYY-MM-DD'), '8 horas', 'CLT', 3500.00, 'Assistência odontológica, vale transporte', 'Rua H, 789, Hospital Animalis', 'Presencial', TO_DATE('2022-02-10', 'YYYY-MM-DD'), 'S', 'S', 'S', 'N', 'Excelente capacidade de lidar com animais e assistência aos veterinários.');




             SELECT *
               FROM dbapa.empresas e,
                    dbapa.funcionarios f
              WHERE e.cd_empresa = f.cd_empresa
                AND e.cd_empresa = 101
                AND Upper(estado_civil) LIKE  Upper('casada')
                AND Upper(f.nm_func) LIKE Upper('%Ana%');



                    SELECT Count(*)
                      FROM dbapa.funcionarios
                      WHERE cd_empresa = 101;